money:
  # monetary-unit: Set what monetary unit you want to use
  monetary-unit: "$"
  # default-money: Set default money when player joined the server first
  default: 1000.0
  # max-money: Set max money that player can have
  max: 9999999999.0
rank:
  # add-op-at-rank: Set whether to show OPs at top money rank
  add-op-at-rank: false
lang:
  # default-lang: Set default language (Available: "ch", "cs", "def", "fr", "id", "it", "jp", "ko", "nl", "ru", "zh")
  default-lang: def
data:
  # auto-save-interval: Set interval of auto-save
  auto-save-interval: 10
  # provider: Set provider of database (Available: yaml)
  provider: yaml
  
